version: "3.8"

services:
  app:
    image: handonggil/flowy-pro:latest
    container_name: my-python-app-container
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SERPAPI_API_KEY=${SERPAPI_API_KEY}
      - CONNECTION_STRING=${CONNECTION_STRING}
    restart: always
