"""create flowy_user table

Revision ID: 9e75a2185d0b
Revises: 2ae75e34bd71
Create Date: 2025-06-02 17:44:09.001113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9e75a2185d0b'
down_revision: Union[str, None] = '2ae75e34bd71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('role_detail', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('project',
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('project_name', sa.String(length=200), nullable=False),
    sa.Column('project_detail', sa.Text(), nullable=True),
    sa.Column('project_created_date', sa.DateTime(), nullable=False),
    sa.Column('project_updated_date', sa.DateTime(), nullable=True),
    sa.Column('project_end_date', sa.DateTime(), nullable=True),
    sa.Column('project_status', sa.BOOLEAN(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.company_id'], ),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('meeting',
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('meeting_title', sa.String(length=150), nullable=False),
    sa.Column('meeting_agenda', sa.String(length=1000), nullable=True),
    sa.Column('meeting_date', sa.TIMESTAMP(), nullable=False),
    sa.Column('meeting_audio_path', sa.Text(), nullable=False),
    sa.Column('meeting_audio_type', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.PrimaryKeyConstraint('meeting_id')
    )
    op.create_table('project_user',
    sa.Column('project_user_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['project.project_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flowy_user.user_id'], ),
    sa.PrimaryKeyConstraint('project_user_id')
    )
    op.create_table('meeting_user',
    sa.Column('meeting_user_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.role_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['flowy_user.user_id'], ),
    sa.PrimaryKeyConstraint('meeting_user_id')
    )
    op.create_table('summary_log',
    sa.Column('summary_log_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('updated_summary_contents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_summary_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], ),
    sa.PrimaryKeyConstraint('summary_log_id')
    )
    op.create_table('task_assign_log',
    sa.Column('task_assign_log_id', sa.UUID(), nullable=False),
    sa.Column('meeting_id', sa.UUID(), nullable=True),
    sa.Column('updated_task_assign_contents', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_task_assign_date', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.meeting_id'], ),
    sa.PrimaryKeyConstraint('task_assign_log_id')
    )
    # op.drop_table('langchain_pg_collection')
    # op.drop_table('test2')
    # op.drop_table('langchain_pg_embedding')
    # op.drop_index(op.f('ix_documents_id'), table_name='documents')
    # op.drop_table('documents')
    # op.drop_table('test')
    # op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('users_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey'),
    sa.UniqueConstraint('email', name='users_email_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('username', name='users_username_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('test',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test_pk'))
    )
    op.create_table('documents',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('original_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('stored_filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('s3_key', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('s3_bucket', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('file_size', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('upload_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_accessed', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('documents_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('documents_pkey')),
    sa.UniqueConstraint('stored_filename', name=op.f('documents_stored_filename_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    op.create_table('langchain_pg_embedding',
    sa.Column('collection_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=True),
    sa.Column('document', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('custom_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['langchain_pg_collection.uuid'], name=op.f('langchain_pg_embedding_collection_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_embedding_pkey'))
    )
    op.create_table('test2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('test2_pk'))
    )
    op.create_table('langchain_pg_collection',
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cmetadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('uuid', sa.UUID(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('langchain_pg_collection_pkey'))
    )
    op.drop_table('task_assign_log')
    op.drop_table('summary_log')
    op.drop_table('meeting_user')
    op.drop_table('project_user')
    op.drop_table('meeting')
    op.drop_table('project')
    op.drop_table('role')
    # ### end Alembic commands ###
