name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v3

    # - name: Install jq
    #   run: sudo apt-get update && sudo apt-get install -y jq

    # - name: Update Security Group with GitHub Actions IPs
    #   env:
    #     AWS_REGION: ap-northeast-2
    #     SECURITY_GROUP_ID: ${{ secrets.AWS_SECURITY_GROUP_ID }}
    #   run: |
    #     aws configure set region $AWS_REGION
    #     chmod +x ./update_sg.sh
    #     ./update_sg.sh  # 위 스크립트 파일로 저장해서 repo에 포함하거나 직접 넣어도 됨

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: handonggil/flowy-pro:latest

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/app  # EC2에 docker-compose.yml이 위치한 디렉터리로 이동
          
          docker-compose pull  # 최신 이미지 가져오기
          
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
          SERPAPI_API_KEY=${{ secrets.SERPAPI_API_KEY }} \
          CONNECTION_STRING=${{ secrets.CONNECTION_STRING }} \
          docker-compose up -d --remove-orphans
